// library my_prj.globals;

String baseUrl = "https://indiajobin.com/admin";
String login = baseUrl + "/seeker-login";
String register = baseUrl + "/seeker";
String country = baseUrl + "/countries/all";
String state = baseUrl + "/states/individual?id=";
String city = baseUrl + "/cities/individual?id=";
String skills = baseUrl + '/skills/all';
String profile = baseUrl + "/update-seeker-additional-details";
String pvtJobListing = baseUrl + "/joblisting/private?student_email=";
String govtJobListing = baseUrl + '/joblisting/government?student_email=';
String privateJobApply = baseUrl + "/apply";
String createOrderId = baseUrl + '/create-order';
String saveOrder = baseUrl + '/save-order';
String oneMonthFree = baseUrl + "/apply-for-free-trial";
String updateUserProfile = baseUrl + '/update-seeker-additional-details';
String getUserProfile = baseUrl + '/seekers?email=';
String updateProfilePic = baseUrl + '/update-seeker-logo';
String logout = baseUrl + '/seeker-logout';
String forgotPassword = baseUrl + '/forgot-password';
